Dbp 000 generate helm doc on pr
dBildungsplattform/dbp-moodle pull request #60
Opened 2024-10-09 13:22 UTC by JannikBadenhop

# Description

## Links to Tickets or other PRs

## Notes

## Approval for review

- [ ] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-10-09 13:47 UTC, marhode approved these changes

2024-10-10 09:50 UTC, maxi418 requested changes

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- all plugins are disabled by default. if enabled, the plugin is installed on image startup
```suggestion
  # -- All plugins are disabled by default. if enabled, the plugin is installed on image startup
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- default storage class, should support ReadWriteMany
```suggestion
  # -- Default storage class, should support ReadWriteMany
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- configurations for the optional redis
```suggestion
  # -- Configurations for the optional redis
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- Create a secret with for all moodle relevant credentials, set useChartSecret: false to provide your own secret
```suggestion
  # -- Creates a secret with all relevant credentials for moodle
  # -- Set useChartSecret: false to provide your own secret
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- if you create your own secret, also set moodle.existingSecret and moodle.externalDatabase.existingSecret (if you bring your own DB)
i think this does not belong here

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # -- which kubectl image to use
```suggestion
    # -- Which kubectl image to use
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- Creates a backup of moodle data & postgres. see backup-cronjob for more values (such as schedule)
```suggestion
  # -- Backup configuration. Determines if the backup-cronjob is enabled, which secrets are used and where the backup is stored.
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +      # -- existing secret for gpg keys
```suggestion
      # -- Existing secret for gpg keys
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # -- either provide an existing secret, or set each secret value here. If both are set the existingSecret is used
```suggestion
    # -- Either provide an existing secret for the s3 endpoint, or provide secret values and let the helm chart create a secret
    # -- If both are set no secret is created and the existingSecret is used
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +      # -- provide a secret with the three keys above
```suggestion
      # -- Existing secret for s3 endpoint
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- This restores moodle to the latest snapshot. ONLY USE FOR ROLLBACK
```suggestion
  # -- This restores moodle to the latest snapshot. Requires that the backup is properly configured. ONLY USE FOR ROLLBACK
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- cronjob to sync moodle users, needs to run regularly if moodle doesn't run as root
```suggestion
  # -- Configuration for the moodle-cronjob which runs moodles cron.php. This is required since moodle does not run as root.
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +  # -- Horizontal Pod Autoscaling Values
```suggestion
  # -- Horizontal pod autoscaling values
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # -- The dbp Image which is build for this Helm Chart
```suggestion
    # -- The dbp-moodle image which is build for this helm chart
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # -- Debug mode for more detailed Moodle installation and log output
```suggestion
    # -- Debug mode for more detailed moodle installation and log output
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # --	If this value is unset, the bitnami/moodle chart generates its own PV & PVC
```suggestion
    # -- If this value is unset, the bitnami/moodle chart generates its own PV & PVC
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # -- 	Password for the above username
```suggestion
    # -- Password for the above username
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # -- The hostname of the moodle application.
```suggestion
    # -- The hostname of the moodle application
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +    # -- Resources have to be set so that the Horizontal Pod Autoscaler for moodle can read the moodle cpu consumption correctly
```suggestion
    # -- Resources have to be set so that the horizontal pod autoscaler for moodle can read the moodle cpu consumption correctly
```

2024-10-10 09:50 UTC, maxi418 commented on charts/dbp-moodle/values.yaml
> +          # -- The custom config.php File that is used to configure Moodle to use the Database and Redis (If activated)
```suggestion
          # -- The custom config.php file that is used to configure moodle to use the database and redis (if activated)
```

2024-10-10 12:11 UTC, maxi418 approved these changes

2024-10-11 08:37 UTC, merged